on:
  push:
    tags:
      - 'v*'
    branch:
      - main

jobs:
  ubuntu24-amd64:
    runs-on: self-hosted
    env:
      ImageOS: ubuntu24
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@main
        with:
          otp-version: '26'
          rebar3-version: '3.16.1'
      - run: |
          rebar3 as prod release
          tar zcf osn-${GITHUB_REF_NAME#v}-ubuntu-noble-x86_64.tar.gz -C _build/prod/rel/ osn
          md5sum osn-${GITHUB_REF_NAME#v}-ubuntu-noble-x86_64.tar.gz | cut -f1 -d ' ' > osn-${GITHUB_REF_NAME#v}-ubuntu-noble-x86_64.md5sum
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            osn-*
  ubuntu22-amd64:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '26'
          rebar3-version: '3.16.1'
      - run: |
          rebar3 as prod release
          tar zcf osn-${GITHUB_REF_NAME#v}-ubuntu-jammy-x86_64.tar.gz -C _build/prod/rel/ osn
          md5sum osn-${GITHUB_REF_NAME#v}-ubuntu-jammy-x86_64.tar.gz | cut -f1 -d ' ' > osn-${GITHUB_REF_NAME#v}-ubuntu-jammy-x86_64.md5sum
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            osn-*
  ubuntu20-amd64:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '26'
          rebar3-version: '3.16.1'
      - run: |
          rebar3 as prod release
          tar zcf osn-${GITHUB_REF_NAME#v}-ubuntu-focal-x86_64.tar.gz -C _build/prod/rel/ osn
          md5sum osn-${GITHUB_REF_NAME#v}-ubuntu-focal-x86_64.tar.gz | cut -f1 -d ' ' > osn-${GITHUB_REF_NAME#v}-ubuntu-focal-x86_64.md5sum
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            osn-*
